(defun evalOp (op a b)
  (funcall (symbol-function op) a b))

(defparameter *ops* '(+ -))

(defun main()
  (let ((d1 (- (char-int (read-char)) 48))
        (d2 (- (char-int (read-char)) 48))
        (d3 (- (char-int (read-char)) 48))
        (d4 (- (char-int (read-char)) 48))
        )
    ; (princ (+ d1 d2))
    (princ (evalOp '+' d1 d2))
    )
  )
(main)
